# for module compiling
import os
from building import *

objs = []

cwd  = GetCurrentDir()

# objs = objs + SConscript(os.path.join(cwd, 'soc', 'bl602', 'std', 'SConscript'))
# objs = objs + SConscript(os.path.join(cwd, 'soc', 'bl616', 'std', 'SConscript'))
# objs = objs + SConscript(os.path.join(cwd, 'soc', 'bl702', 'std', 'SConscript'))
objs = objs + SConscript(os.path.join(cwd, 'soc', 'bl808', 'std', 'SConscript'))
objs = objs + SConscript(os.path.join(cwd, 'lhal', 'SConscript'))

Return('objs')
